// AUTO-GENERATED by scripts/build-powerbi-pl.py — DO NOT EDIT BY HAND.
// Static Power BI export snapshots (one per financial year) for the
// "Power BI Version" reference table on the E.M Bakış dashboard. Re-run the
// script after adding/replacing a "Live Realized - Projected P&L … .xlsx" pair.

export interface PowerBIPLMonthRow {
  /** 'YYYY-MM' of the FY month. */
  monthKey: string;
  projQtyTons: number;
  projRevenueUsd: number;
  projPLUsd: number;
  budgetUsd: number;
  realQtyTons: number;
  realRevenueUsd: number;
  realPLUsd: number;
}

export interface PowerBIPLSegmentRow {
  segment: string;
  projPLUsd: number;
  realPLUsd: number;
  budgetUsd: number;
}

export interface PowerBIPLYear {
  /** FinancialYear.label this snapshot belongs to (e.g. '25-26'). */
  fy: string;
  /** 12 FY-month rows, Jul → Jun. */
  rows: PowerBIPLMonthRow[];
  /** monthKey → per-segment breakdown (drill-down). */
  segments: Record<string, PowerBIPLSegmentRow[]>;
}

/** Every FY export we have, keyed by FinancialYear.label. The dashboard
 *  renders the Power BI Version table only for a selected FY that is a key
 *  here. */
export const POWERBI_PL_BY_FY: Record<string, PowerBIPLYear> = {
  "24-25": {
    fy: "24-25",
    rows: [
      { monthKey: "2024-07", projQtyTons: 202000, projRevenueUsd: 93858944.443501, projPLUsd: 1823909.93582, budgetUsd: 0, realQtyTons: 53870.408, realRevenueUsd: 37650014.6, realPLUsd: 10103516.314106 },
      { monthKey: "2024-08", projQtyTons: 141150.964, projRevenueUsd: 84735418.330925, projPLUsd: -31957125.388493, budgetUsd: 0, realQtyTons: 51322.56, realRevenueUsd: 14394230.3, realPLUsd: 323355.580317 },
      { monthKey: "2024-09", projQtyTons: 131500, projRevenueUsd: 53046527, projPLUsd: -495411992.3798, budgetUsd: 0, realQtyTons: 454997.826, realRevenueUsd: 196163922.994137, realPLUsd: 10625705.163335 },
      { monthKey: "2024-10", projQtyTons: 322178.6, projRevenueUsd: 9814306279.944616, projPLUsd: -656911115.64377, budgetUsd: 0, realQtyTons: 84875.51, realRevenueUsd: 39617561.4101, realPLUsd: 1982322.13983 },
      { monthKey: "2024-11", projQtyTons: 150423.905, projRevenueUsd: 273169055.159513, projPLUsd: -4698867.676661, budgetUsd: 0, realQtyTons: 365405.267, realRevenueUsd: 140277941.518842, realPLUsd: 2532962.246241 },
      { monthKey: "2024-12", projQtyTons: 261835, projRevenueUsd: 115620344.565029, projPLUsd: -33902958.11699, budgetUsd: 0, realQtyTons: 80035.62, realRevenueUsd: 39975774.38, realPLUsd: 1725184.122949 },
      { monthKey: "2025-01", projQtyTons: 145021.673, projRevenueUsd: 50441385.71, projPLUsd: -9422381.06778, budgetUsd: 0, realQtyTons: 81329.46494, realRevenueUsd: 30861281.64, realPLUsd: 2209827.548477 },
      { monthKey: "2025-02", projQtyTons: 46006.3, projRevenueUsd: 13293160.8, projPLUsd: 477066.94, budgetUsd: 0, realQtyTons: 56865.3, realRevenueUsd: 26739752.24, realPLUsd: 5279226.729089 },
      { monthKey: "2025-03", projQtyTons: 57601, projRevenueUsd: 66986763.903367, projPLUsd: -665882.863775, budgetUsd: 0, realQtyTons: 155461.725, realRevenueUsd: 59867123.833362, realPLUsd: 4345813.996358 },
      { monthKey: "2025-04", projQtyTons: 122236.35, projRevenueUsd: 35845392.435, projPLUsd: 2988408.75, budgetUsd: 0, realQtyTons: 10100, realRevenueUsd: 1777400, realPLUsd: 84696.344353 },
      { monthKey: "2025-05", projQtyTons: 191397, projRevenueUsd: 102657860.4, projPLUsd: 4324570.88986, budgetUsd: 0, realQtyTons: 256658.398, realRevenueUsd: 138952167.425298, realPLUsd: 7936581.654815 },
      { monthKey: "2025-06", projQtyTons: 299448.5, projRevenueUsd: 126956245.465298, projPLUsd: 6487944.091861, budgetUsd: -42235000, realQtyTons: 160100.584, realRevenueUsd: 55717643.11, realPLUsd: 4346746.250109 },
    ],
    segments: {
      "2024-07": [
        { segment: "Central America", projPLUsd: 895342.28232, realPLUsd: 853584.123008, budgetUsd: 0 },
        { segment: "Iran payment", projPLUsd: -2983853.5465, realPLUsd: 0, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 3912421.2, realPLUsd: 9249932.191098, budgetUsd: 0 },
      ],
      "2024-08": [
        { segment: "Arasa-Trabzon", projPLUsd: -5667648.88, realPLUsd: 329806.097797, budgetUsd: 0 },
        { segment: "Central America", projPLUsd: 159315, realPLUsd: 0, budgetUsd: 0 },
        { segment: "Iran payment", projPLUsd: -26448791.508493, realPLUsd: 0, budgetUsd: 0 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: -6450.51748, budgetUsd: 0 },
      ],
      "2024-09": [
        { segment: "Arasa-Trabzon", projPLUsd: -1282685.8498, realPLUsd: 1581867.236673, budgetUsd: 0 },
        { segment: "Central America", projPLUsd: 0, realPLUsd: 572273.179803, budgetUsd: 0 },
        { segment: "Iran payment", projPLUsd: 0, realPLUsd: 4269144.840157, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: -4757306.53, realPLUsd: 4260154.086383, budgetUsd: 0 },
        { segment: "Iraq Wheat", projPLUsd: -489372000, realPLUsd: -57734.179681, budgetUsd: 0 },
      ],
      "2024-10": [
        { segment: "Arasa-Trabzon", projPLUsd: -65753.64, realPLUsd: 203931.181454, budgetUsd: 0 },
        { segment: "Iran payment", projPLUsd: 1416821.24349, realPLUsd: 0, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: -658576941.85366, realPLUsd: 1778390.958376, budgetUsd: 0 },
        { segment: "Iraq Wheat", projPLUsd: 314758.6064, realPLUsd: 0, budgetUsd: 0 },
      ],
      "2024-11": [
        { segment: "Arasa-Trabzon", projPLUsd: 0, realPLUsd: 176745.533237, budgetUsd: 0 },
        { segment: "Iran payment", projPLUsd: -185234.401661, realPLUsd: 1745506.786474, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: -4513633.275, realPLUsd: 1552979.779437, budgetUsd: 0 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: -942269.852907, budgetUsd: 0 },
      ],
      "2024-12": [
        { segment: "Arasa-Trabzon", projPLUsd: -10100000, realPLUsd: 221461.232949, budgetUsd: 0 },
        { segment: "Central America", projPLUsd: -4925000, realPLUsd: 247386.67, budgetUsd: 0 },
        { segment: "Iran payment", projPLUsd: 762372.04869, realPLUsd: 0, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: -21512167.86568, realPLUsd: 1256336.22, budgetUsd: 0 },
        { segment: "Iraq Wheat", projPLUsd: 1871837.7, realPLUsd: 0, budgetUsd: 0 },
      ],
      "2025-01": [
        { segment: "Arasa-Trabzon", projPLUsd: 309345, realPLUsd: 764928.718477, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 3622273.93222, realPLUsd: 1444898.83, budgetUsd: 0 },
        { segment: "Iraq Wheat", projPLUsd: -13354000, realPLUsd: 0, budgetUsd: 0 },
      ],
      "2025-02": [
        { segment: "Arasa-Trabzon", projPLUsd: -851427.36, realPLUsd: 4159428.979089, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 1328494.3, realPLUsd: 1119797.75, budgetUsd: 0 },
      ],
      "2025-03": [
        { segment: "Arasa-Trabzon", projPLUsd: 182750.857325, realPLUsd: 258904.790219, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: -848633.7211, realPLUsd: 4086909.206139, budgetUsd: 0 },
      ],
      "2025-04": [
        { segment: "Arasa-Trabzon", projPLUsd: 240000, realPLUsd: 84696.344353, budgetUsd: 0 },
        { segment: "Eritrea", projPLUsd: 742500, realPLUsd: 0, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 2005908.75, realPLUsd: 0, budgetUsd: 0 },
      ],
      "2025-05": [
        { segment: "Central America", projPLUsd: 1907462.17741, realPLUsd: 1679778.039227, budgetUsd: 0 },
        { segment: "Iran payment", projPLUsd: 0, realPLUsd: 1395934.885588, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 2417108.71245, realPLUsd: 4860868.73, budgetUsd: 0 },
      ],
      "2025-06": [
        { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: -2424000 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: -2700000 },
        { segment: "Eritrea", projPLUsd: 0, realPLUsd: 711368.008434, budgetUsd: -900000 },
        { segment: "Ghana", projPLUsd: 0, realPLUsd: 0, budgetUsd: -673000 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: 4498000 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -4496000 },
        { segment: "Iran payment", projPLUsd: 1849509.883861, realPLUsd: 0, budgetUsd: -7200000 },
        { segment: "Iraq", projPLUsd: 3186434.208, realPLUsd: 3635378.241675, budgetUsd: -28340000 },
        { segment: "Iraq Wheat", projPLUsd: 1452000, realPLUsd: 0, budgetUsd: 0 },
      ],
    },
  },
  "25-26": {
    fy: "25-26",
    rows: [
      { monthKey: "2025-07", projQtyTons: 126434, projRevenueUsd: 40049553.4, projPLUsd: 3848212.205, budgetUsd: 6264198, realQtyTons: 127034.06, realRevenueUsd: 40049553.4, realPLUsd: 3877077.121933 },
      { monthKey: "2025-08", projQtyTons: 331295.5, projRevenueUsd: 116986185.306875, projPLUsd: 4886760.72, budgetUsd: 3159455, realQtyTons: 456857.367, realRevenueUsd: 174487288.338012, realPLUsd: 10269650.01451 },
      { monthKey: "2025-09", projQtyTons: 369319.77, projRevenueUsd: 140965712.631142, projPLUsd: 7858621.713103, budgetUsd: 3917268, realQtyTons: 276502.505, realRevenueUsd: 106367661.791025, realPLUsd: 6141779.889135 },
      { monthKey: "2025-10", projQtyTons: 300868.695, projRevenueUsd: 100288484.726429, projPLUsd: 7818075.8104, budgetUsd: 8002294, realQtyTons: 312905.049, realRevenueUsd: 104314830.235403, realPLUsd: 8094739.395992 },
      { monthKey: "2025-11", projQtyTons: 250944.615, projRevenueUsd: 113043638.71, projPLUsd: 13992647.8581, budgetUsd: 4764659, realQtyTons: 314119.656, realRevenueUsd: 155282888.51, realPLUsd: 22952749.576396 },
      { monthKey: "2025-12", projQtyTons: 266939.96, projRevenueUsd: 128592263.77, projPLUsd: 15263429.80432, budgetUsd: 5201472, realQtyTons: 145252.339, realRevenueUsd: 56182205.12, realPLUsd: 3729208.604425 },
      { monthKey: "2026-01", projQtyTons: 372140.942, projRevenueUsd: 143796544.04, projPLUsd: 10164276.77858, budgetUsd: 3899411, realQtyTons: 350623.543, realRevenueUsd: 125721070.051983, realPLUsd: 8037383.667653 },
      { monthKey: "2026-02", projQtyTons: 186556.98, projRevenueUsd: 76445829.301984, projPLUsd: 4086605.33, budgetUsd: 6214455, realQtyTons: 186700, realRevenueUsd: 60288712.5, realPLUsd: 3230209.796046 },
      { monthKey: "2026-03", projQtyTons: 3300, projRevenueUsd: 976800, projPLUsd: 257400, budgetUsd: 4630808, realQtyTons: 7566.98, realRevenueUsd: 1522973.44, realPLUsd: 15244.55379 },
      { monthKey: "2026-04", projQtyTons: 30000, projRevenueUsd: 9825958.27, projPLUsd: 1003959.6, budgetUsd: 4764194, realQtyTons: 83248.838, realRevenueUsd: 35832681.67, realPLUsd: 2418030.456931 },
      { monthKey: "2026-05", projQtyTons: 170778.393, projRevenueUsd: 81560013.120632, projPLUsd: 7193809.5919, budgetUsd: 5270617, realQtyTons: 182774.893, realRevenueUsd: 76111921.328856, realPLUsd: 4511645.635932 },
      { monthKey: "2026-06", projQtyTons: 92639.513, projRevenueUsd: 53485903.626945, projPLUsd: 3434483.605695, budgetUsd: 6017015, realQtyTons: 8329.74, realRevenueUsd: 7109923.56, realPLUsd: 800781.613874 },
    ],
    segments: {
      "2025-07": [
        { segment: "Arasa-Trabzon", projPLUsd: 0, realPLUsd: 0, budgetUsd: 85706 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225294 },
        { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: 2159945 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 309590 },
        { segment: "Eritrea", projPLUsd: 128539.1, realPLUsd: 161716.932553, budgetUsd: 572000 },
        { segment: "Ghana", projPLUsd: 308, realPLUsd: 1410, budgetUsd: 0 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -199041 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -43296 },
        { segment: "Iraq", projPLUsd: 1995262.84, realPLUsd: 2118427.46938, budgetUsd: 2990000 },
        { segment: "Iraq Wheat", projPLUsd: 1724102.265, realPLUsd: 1595522.72, budgetUsd: 164000 },
      ],
      "2025-08": [
        { segment: "Arasa-Trabzon", projPLUsd: 0, realPLUsd: 0, budgetUsd: 85763 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225569 },
        { segment: "Central America", projPLUsd: 231116.75, realPLUsd: 1431143.182393, budgetUsd: -246800 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 229135 },
        { segment: "Eritrea", projPLUsd: 716408, realPLUsd: 0, budgetUsd: 0 },
        { segment: "Ghana", projPLUsd: 2288, realPLUsd: 0, budgetUsd: 0 },
        { segment: "International", projPLUsd: -512850, realPLUsd: -466215.04, budgetUsd: -211714 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 2452277.020679, budgetUsd: -43998 },
        { segment: "Iran payment", projPLUsd: 471466.88, realPLUsd: 798275.177588, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 3978331.09, realPLUsd: 6054169.67385, budgetUsd: 2957500 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 164000 },
      ],
      "2025-09": [
        { segment: "Arasa-Trabzon", projPLUsd: 292243.531, realPLUsd: 274638.003518, budgetUsd: 85699 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225235 },
        { segment: "Central America", projPLUsd: 29193.37855, realPLUsd: 0, budgetUsd: -246983 },
        { segment: "Djibouti", projPLUsd: 314975.7394, realPLUsd: 768010.3, budgetUsd: 293447 },
        { segment: "Eritrea", projPLUsd: 0, realPLUsd: 1061807.050021, budgetUsd: 632000 },
        { segment: "Ghana", projPLUsd: 0, realPLUsd: 5690.06, budgetUsd: 0 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -176890 },
        { segment: "Iran", projPLUsd: 1472006.5728, realPLUsd: 0, budgetUsd: -49240 },
        { segment: "Iran payment", projPLUsd: 616729.058453, realPLUsd: 634306.576559, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 5045873.4329, realPLUsd: 2710763.729037, budgetUsd: 2990000 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 164000 },
        { segment: "Nigeria", projPLUsd: 87600, realPLUsd: 686564.17, budgetUsd: 0 },
      ],
      "2025-10": [
        { segment: "Arasa-Trabzon", projPLUsd: 264630.27484, realPLUsd: 198750.136851, budgetUsd: 85746 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225479 },
        { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: 3060246 },
        { segment: "Djibouti", projPLUsd: 233400, realPLUsd: 51493.18, budgetUsd: 229160 },
        { segment: "Ghana", projPLUsd: 11550, realPLUsd: 0, budgetUsd: 0 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -104027 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -47310 },
        { segment: "Iran payment", projPLUsd: 4093643.35236, realPLUsd: 3553222.34796, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 3214852.1832, realPLUsd: 4471334.661181, budgetUsd: 4030000 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: -180060.93, budgetUsd: 523000 },
      ],
      "2025-11": [
        { segment: "Arasa-Trabzon", projPLUsd: 200948.3706, realPLUsd: 775134.99758, budgetUsd: 85778 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225587 },
        { segment: "Central America", projPLUsd: 8331390, realPLUsd: 17255701.414086, budgetUsd: -246639 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 340818 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -146595 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -47290 },
        { segment: "Iraq", projPLUsd: 4169509.4875, realPLUsd: 5427297.88473, budgetUsd: 4030000 },
        { segment: "Iraq Wheat", projPLUsd: 1290800, realPLUsd: 0, budgetUsd: 523000 },
        { segment: "Nigeria", projPLUsd: 0, realPLUsd: -505384.72, budgetUsd: 0 },
      ],
      "2025-12": [
        { segment: "Arasa-Trabzon", projPLUsd: 197477.5728, realPLUsd: 111211.879083, budgetUsd: 85803 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225720 },
        { segment: "Central America", projPLUsd: 8841300, realPLUsd: 0, budgetUsd: 1424486 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 199716 },
        { segment: "Eritrea", projPLUsd: 0, realPLUsd: 0, budgetUsd: 632000 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -149543 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -47210 },
        { segment: "Iraq", projPLUsd: 5455602.23152, realPLUsd: 3617996.725342, budgetUsd: 2307500 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 523000 },
        { segment: "Nigeria", projPLUsd: 769050, realPLUsd: 0, budgetUsd: 0 },
      ],
      "2026-01": [
        { segment: "Arasa-Trabzon", projPLUsd: 809338.021, realPLUsd: 386024.536091, budgetUsd: 85292 },
        { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: -253457 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 302063 },
        { segment: "Eritrea", projPLUsd: 0, realPLUsd: 0, budgetUsd: 572000 },
        { segment: "Ghana", projPLUsd: 46310, realPLUsd: -1022.2, budgetUsd: 0 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -245197.0 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -47290 },
        { segment: "Iran payment", projPLUsd: 0, realPLUsd: 937418.442528, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 9308628.75758, realPLUsd: 6714962.889034, budgetUsd: 2990000 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 496000 },
      ],
      "2026-02": [
        { segment: "Arasa-Trabzon", projPLUsd: 157878.26, realPLUsd: 156693.310026, budgetUsd: 85345 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 223909 },
        { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: 1381804 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225496 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -170259 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -57840 },
        { segment: "Iran payment", projPLUsd: 1220903.97, realPLUsd: 0, budgetUsd: 0 },
        { segment: "Iraq", projPLUsd: 2707823.1, realPLUsd: 3073516.48602, budgetUsd: 4030000 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 496000 },
      ],
      "2026-03": [
        { segment: "Arasa-Trabzon", projPLUsd: 257400, realPLUsd: 15244.55379, budgetUsd: 85399 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 223536 },
        { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: -253099 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 338214 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -193936 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -95306 },
        { segment: "Iraq", projPLUsd: 0, realPLUsd: 0, budgetUsd: 4030000 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 496000 },
      ],
      "2026-04": [
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 224411 },
        { segment: "Central America", projPLUsd: 1003959.6, realPLUsd: 1101445.24, budgetUsd: -252473 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 228414 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -188000 },
        { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -54705 },
        { segment: "Iraq", projPLUsd: 0, realPLUsd: 1232666.2, budgetUsd: 4225000.0 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 496000 },
      ],
      "2026-05": [
        { segment: "Arasa-Trabzon", projPLUsd: 3396766.18, realPLUsd: 0, budgetUsd: 0 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 224628 },
        { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: -252269 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 309807 },
        { segment: "Eritrea", projPLUsd: 1235428.18455, realPLUsd: 1212058.376278, budgetUsd: 572000 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -160432 },
        { segment: "Iran", projPLUsd: 92222.45835, realPLUsd: 84545.408856, budgetUsd: -54705 },
        { segment: "Iraq", projPLUsd: 2469392.769, realPLUsd: 2585320.66, budgetUsd: 4030000 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 516000 },
      ],
      "2026-06": [
        { segment: "Arasa-Trabzon", projPLUsd: 1181886, realPLUsd: 0, budgetUsd: 0 },
        { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 224775 },
        { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: 1382851 },
        { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225740 },
        { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -393252 },
        { segment: "Iran", projPLUsd: 822000, realPLUsd: 0, budgetUsd: -54707 },
        { segment: "Iraq", projPLUsd: 1430597.605695, realPLUsd: 282366.6, budgetUsd: 4030000 },
        { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 516000 },
      ],
    },
  },
};
