/**
 * "Power BI Version" tables — FIXED reference snapshots of the Power BI
 * "LIVE REALIZED – PROJECTED P&L" export, one per financial year, rendered
 * next to the live (our-system) tables on the E.M Bakış dashboard so the two
 * can be eyeballed side by side.
 *
 * Unlike `buildRealizedPLTable`, these are NOT computed from projects: they
 * reshape the static `src/data/powerbiPL.ts` (generated by
 * `scripts/build-powerbi-pl.py` from the Excel exports) into the SAME
 * `RealizedPLTableData` shape so they can reuse the exact same
 * `RealizedPLTable` component. Each snapshot belongs to ONE financial year and
 * the dashboard only shows it when that FY is the selected filter (a 25-26
 * export is meaningless under a 24-25 filter). Row drill-down comes from the
 * detailed-matrix export (per-segment), via `getPowerBISegments`.
 */
import {
  POWERBI_PL_BY_FY,
  type PowerBIPLSegmentRow,
} from "@/data/powerbiPL";
import type {
  RealizedPLMonthRow,
  RealizedPLTableData,
} from "./realizedPLTable";
import type { MonthlyPLPoint } from "./monthlyPL";

const MONTH_FMT = new Intl.DateTimeFormat("tr-TR", { month: "short" });

/** "2025-07" → "Tem-25" (same label dialect as the live table). */
function labelOf(monthKey: string): string {
  const [y, m] = monthKey.split("-").map(Number);
  const d = new Date(y, m - 1, 1);
  return `${MONTH_FMT.format(d)}-${String(y).slice(-2)}`;
}

/** FinancialYear.label values we have a Power BI export for (e.g.
 *  ["24-25", "25-26"]). */
export const POWERBI_PL_FYS = Object.keys(POWERBI_PL_BY_FY);

/** Whether a Power BI Version snapshot exists for this FY label. */
export function hasPowerBIPL(fy: string): boolean {
  return fy in POWERBI_PL_BY_FY;
}

/** Reshape the static PBI export for `fy` into `RealizedPLTableData`, or null
 *  when there's no export for that year. `totalLabel` is the localized
 *  "Toplam" footer label passed by the caller. */
export function buildPowerBIPLTable(
  fy: string,
  totalLabel = "Toplam"
): RealizedPLTableData | null {
  const year = POWERBI_PL_BY_FY[fy];
  if (!year) return null;

  const rows: RealizedPLMonthRow[] = year.rows.map((r) => ({
    monthKey: r.monthKey,
    monthLabel: labelOf(r.monthKey),
    projQtyTons: r.projQtyTons,
    projRevenueUsd: r.projRevenueUsd,
    projPLUsd: r.projPLUsd,
    budgetUsd: r.budgetUsd,
    realQtyTons: r.realQtyTons,
    realRevenueUsd: r.realRevenueUsd,
    realPLUsd: r.realPLUsd,
    plToBudgetPct: r.budgetUsd !== 0 ? (r.realPLUsd / r.budgetUsd) * 100 : null,
    isFuture: false,
    // Drives the clickable chevron — segment count standing in for the
    // per-project count the live table shows.
    projectCount: (year.segments[r.monthKey] ?? []).length,
  }));

  const sum = (k: keyof RealizedPLMonthRow) =>
    rows.reduce((s, r) => s + (Number(r[k]) || 0), 0);

  const totalBudget = sum("budgetUsd");
  const totalRealPL = sum("realPLUsd");
  const total: RealizedPLMonthRow = {
    monthKey: "TOTAL",
    monthLabel: totalLabel,
    projQtyTons: sum("projQtyTons"),
    projRevenueUsd: sum("projRevenueUsd"),
    projPLUsd: sum("projPLUsd"),
    budgetUsd: totalBudget,
    realQtyTons: sum("realQtyTons"),
    realRevenueUsd: sum("realRevenueUsd"),
    realPLUsd: totalRealPL,
    plToBudgetPct: totalBudget !== 0 ? (totalRealPL / totalBudget) * 100 : null,
    isFuture: false,
    projectCount: 0,
  };

  return { rows, total };
}

/** Per-segment breakdown for one month's drill-down (from the detailed
 *  matrix). Empty array when the FY or month key is unknown. */
export function getPowerBISegments(
  fy: string,
  monthKey: string
): PowerBIPLSegmentRow[] {
  return POWERBI_PL_BY_FY[fy]?.segments[monthKey] ?? [];
}

/** Monthly estimated-vs-realized P&L points for the "Aylık P&L Performansı"
 *  chart, sourced from the PBI export for `fy`. null when there's no export
 *  (the caller then falls back to the live `aggregateMonthlyPL`). Projected
 *  P&L → estPL, Live Realized P&L → realizedPL. Everything is historical
 *  (isFuture false); no per-project count in the export → realizedCount 0. */
export function buildPowerBIMonthlyPL(fy: string): MonthlyPLPoint[] | null {
  const year = POWERBI_PL_BY_FY[fy];
  if (!year) return null;
  const fmt = new Intl.DateTimeFormat("tr-TR", { month: "short" });
  return year.rows.map((r) => {
    const [y, m] = r.monthKey.split("-").map(Number);
    return {
      monthKey: r.monthKey,
      monthLabel: fmt.format(new Date(y, m - 1, 1)),
      estPL: r.projPLUsd,
      realizedPL: r.realPLUsd,
      realizedCount: 0,
      isFuture: false,
    };
  });
}
