/**
 * "Power BI Version" table — a FIXED reference snapshot of the Power BI
 * "LIVE REALIZED – PROJECTED P&L" export for FY 25-26, rendered next to the
 * live (our-system) tables on the E.M Bakış dashboard so the two can be
 * eyeballed side by side.
 *
 * Unlike `buildRealizedPLTable`, this is NOT computed from projects and does
 * NOT react to the page filter / FY selector — it just reshapes the static
 * `src/data/powerbiPL.ts` (generated by `scripts/build-powerbi-pl.py` from the
 * Excel exports) into the SAME `RealizedPLTableData` shape so it can reuse the
 * exact same `RealizedPLTable` component. The row drill-down comes from the
 * detailed-matrix export (per-segment), surfaced by `getPowerBISegments`.
 */
import {
  POWERBI_PL_ROWS,
  POWERBI_PL_SEGMENTS,
  type PowerBIPLSegmentRow,
} from "@/data/powerbiPL";
import type {
  RealizedPLMonthRow,
  RealizedPLTableData,
} from "./realizedPLTable";

/** Financial year this static snapshot represents (matches
 *  `FinancialYear.label`). The dashboard only renders the "Power BI Version"
 *  table when this FY is the selected one — it's a fixed 25-26 export, so it
 *  would be meaningless under any other FY filter. Bump this if the Excel
 *  export is regenerated for a different year. */
export const POWERBI_PL_FY = "25-26";

const MONTH_FMT = new Intl.DateTimeFormat("tr-TR", { month: "short" });

/** "2025-07" → "Tem-25" (same label dialect as the live table). */
function labelOf(monthKey: string): string {
  const [y, m] = monthKey.split("-").map(Number);
  const d = new Date(y, m - 1, 1);
  return `${MONTH_FMT.format(d)}-${String(y).slice(-2)}`;
}

/** Reshape the static PBI export into `RealizedPLTableData`. `totalLabel` is
 *  the localized "Toplam" footer label passed by the caller. */
export function buildPowerBIPLTable(totalLabel = "Toplam"): RealizedPLTableData {
  const rows: RealizedPLMonthRow[] = POWERBI_PL_ROWS.map((r) => ({
    monthKey: r.monthKey,
    monthLabel: labelOf(r.monthKey),
    projQtyTons: r.projQtyTons,
    projRevenueUsd: r.projRevenueUsd,
    projPLUsd: r.projPLUsd,
    budgetUsd: r.budgetUsd,
    realQtyTons: r.realQtyTons,
    realRevenueUsd: r.realRevenueUsd,
    realPLUsd: r.realPLUsd,
    plToBudgetPct: r.budgetUsd !== 0 ? (r.realPLUsd / r.budgetUsd) * 100 : null,
    isFuture: false,
    // Drives the "clickable" chevron — segment count standing in for the
    // per-project count the live table shows.
    projectCount: (POWERBI_PL_SEGMENTS[r.monthKey] ?? []).length,
  }));

  const sum = (k: keyof RealizedPLMonthRow) =>
    rows.reduce((s, r) => s + (Number(r[k]) || 0), 0);

  const totalBudget = sum("budgetUsd");
  const totalRealPL = sum("realPLUsd");
  const total: RealizedPLMonthRow = {
    monthKey: "TOTAL",
    monthLabel: totalLabel,
    projQtyTons: sum("projQtyTons"),
    projRevenueUsd: sum("projRevenueUsd"),
    projPLUsd: sum("projPLUsd"),
    budgetUsd: totalBudget,
    realQtyTons: sum("realQtyTons"),
    realRevenueUsd: sum("realRevenueUsd"),
    realPLUsd: totalRealPL,
    plToBudgetPct: totalBudget !== 0 ? (totalRealPL / totalBudget) * 100 : null,
    isFuture: false,
    projectCount: 0,
  };

  return { rows, total };
}

/** Per-segment breakdown for one month's drill-down (from the detailed
 *  matrix). Empty array when the month key is unknown. */
export function getPowerBISegments(monthKey: string): PowerBIPLSegmentRow[] {
  return POWERBI_PL_SEGMENTS[monthKey] ?? [];
}
