// AUTO-GENERATED by scripts/build-powerbi-pl.py — DO NOT EDIT BY HAND.
// Static Power BI export snapshot (FY 25-26) for the "Power BI Version"
// reference table on the E.M Bakış dashboard. Re-run the script after
// replacing either "Live Realized - Projected P&L … .xlsx" export.

export interface PowerBIPLMonthRow {
  /** 'YYYY-MM' of the FY month. */
  monthKey: string;
  projQtyTons: number;
  projRevenueUsd: number;
  projPLUsd: number;
  budgetUsd: number;
  realQtyTons: number;
  realRevenueUsd: number;
  realPLUsd: number;
}

export interface PowerBIPLSegmentRow {
  segment: string;
  projPLUsd: number;
  realPLUsd: number;
  budgetUsd: number;
}

/** 12 FY-month rows, Jul-25 → Jun-26 (from the main export). */
export const POWERBI_PL_ROWS: PowerBIPLMonthRow[] = [
  { monthKey: "2025-07", projQtyTons: 126434, projRevenueUsd: 40049553.4, projPLUsd: 3848212.205, budgetUsd: 6264198, realQtyTons: 127034.06, realRevenueUsd: 40049553.4, realPLUsd: 3877077.121933 },
  { monthKey: "2025-08", projQtyTons: 331295.5, projRevenueUsd: 116986185.306875, projPLUsd: 4886760.72, budgetUsd: 3159455, realQtyTons: 456857.367, realRevenueUsd: 174487288.338012, realPLUsd: 10269650.01451 },
  { monthKey: "2025-09", projQtyTons: 369319.77, projRevenueUsd: 140965712.631142, projPLUsd: 7858621.713103, budgetUsd: 3917268, realQtyTons: 276502.505, realRevenueUsd: 106367661.791025, realPLUsd: 6141779.889135 },
  { monthKey: "2025-10", projQtyTons: 300868.695, projRevenueUsd: 100288484.726429, projPLUsd: 7818075.8104, budgetUsd: 8002294, realQtyTons: 312905.049, realRevenueUsd: 104314830.235403, realPLUsd: 8094739.395992 },
  { monthKey: "2025-11", projQtyTons: 250944.615, projRevenueUsd: 113043638.71, projPLUsd: 13992647.8581, budgetUsd: 4764659, realQtyTons: 314119.656, realRevenueUsd: 155282888.51, realPLUsd: 22952749.576396 },
  { monthKey: "2025-12", projQtyTons: 266939.96, projRevenueUsd: 128592263.77, projPLUsd: 15263429.80432, budgetUsd: 5201472, realQtyTons: 145252.339, realRevenueUsd: 56182205.12, realPLUsd: 3729208.604425 },
  { monthKey: "2026-01", projQtyTons: 372140.942, projRevenueUsd: 143796544.04, projPLUsd: 10164276.77858, budgetUsd: 3899411, realQtyTons: 350623.543, realRevenueUsd: 125721070.051983, realPLUsd: 8037383.667653 },
  { monthKey: "2026-02", projQtyTons: 186556.98, projRevenueUsd: 76445829.301984, projPLUsd: 4086605.33, budgetUsd: 6214455, realQtyTons: 186700, realRevenueUsd: 60288712.5, realPLUsd: 3230209.796046 },
  { monthKey: "2026-03", projQtyTons: 3300, projRevenueUsd: 976800, projPLUsd: 257400, budgetUsd: 4630808, realQtyTons: 7566.98, realRevenueUsd: 1522973.44, realPLUsd: 15244.55379 },
  { monthKey: "2026-04", projQtyTons: 30000, projRevenueUsd: 9825958.27, projPLUsd: 1003959.6, budgetUsd: 4764194, realQtyTons: 83248.838, realRevenueUsd: 35832681.67, realPLUsd: 2418030.456931 },
  { monthKey: "2026-05", projQtyTons: 170778.393, projRevenueUsd: 81560013.120632, projPLUsd: 7193809.5919, budgetUsd: 5270617, realQtyTons: 182774.893, realRevenueUsd: 76111921.328856, realPLUsd: 4511645.635932 },
  { monthKey: "2026-06", projQtyTons: 92639.513, projRevenueUsd: 53485903.626945, projPLUsd: 3434483.605695, budgetUsd: 6017015, realQtyTons: 8329.74, realRevenueUsd: 7109923.56, realPLUsd: 800781.613874 },
];

/** monthKey → per-segment P&L / budget breakdown (drill-down, from the
 *  detailed-matrix export). Segments with an all-zero month are omitted. */
export const POWERBI_PL_SEGMENTS: Record<string, PowerBIPLSegmentRow[]> = {
  "2025-07": [
    { segment: "Arasa-Trabzon", projPLUsd: 0, realPLUsd: 0, budgetUsd: 85706 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225294 },
    { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: 2159945 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 309590 },
    { segment: "Eritrea", projPLUsd: 128539.1, realPLUsd: 161716.932553, budgetUsd: 572000 },
    { segment: "Ghana", projPLUsd: 308, realPLUsd: 1410, budgetUsd: 0 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -199041 },
    { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -43296 },
    { segment: "Iraq", projPLUsd: 1995262.84, realPLUsd: 2118427.46938, budgetUsd: 2990000 },
    { segment: "Iraq Wheat", projPLUsd: 1724102.265, realPLUsd: 1595522.72, budgetUsd: 164000 },
  ],
  "2025-08": [
    { segment: "Arasa-Trabzon", projPLUsd: 0, realPLUsd: 0, budgetUsd: 85763 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225569 },
    { segment: "Central America", projPLUsd: 231116.75, realPLUsd: 1431143.182393, budgetUsd: -246800 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 229135 },
    { segment: "Eritrea", projPLUsd: 716408, realPLUsd: 0, budgetUsd: 0 },
    { segment: "Ghana", projPLUsd: 2288, realPLUsd: 0, budgetUsd: 0 },
    { segment: "International", projPLUsd: -512850, realPLUsd: -466215.04, budgetUsd: -211714 },
    { segment: "Iran", projPLUsd: 0, realPLUsd: 2452277.020679, budgetUsd: -43998 },
    { segment: "Iran payment", projPLUsd: 471466.88, realPLUsd: 798275.177588, budgetUsd: 0 },
    { segment: "Iraq", projPLUsd: 3978331.09, realPLUsd: 6054169.67385, budgetUsd: 2957500 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 164000 },
  ],
  "2025-09": [
    { segment: "Arasa-Trabzon", projPLUsd: 292243.531, realPLUsd: 274638.003518, budgetUsd: 85699 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225235 },
    { segment: "Central America", projPLUsd: 29193.37855, realPLUsd: 0, budgetUsd: -246983 },
    { segment: "Djibouti", projPLUsd: 314975.7394, realPLUsd: 768010.3, budgetUsd: 293447 },
    { segment: "Eritrea", projPLUsd: 0, realPLUsd: 1061807.050021, budgetUsd: 632000 },
    { segment: "Ghana", projPLUsd: 0, realPLUsd: 5690.06, budgetUsd: 0 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -176890 },
    { segment: "Iran", projPLUsd: 1472006.5728, realPLUsd: 0, budgetUsd: -49240 },
    { segment: "Iran payment", projPLUsd: 616729.058453, realPLUsd: 634306.576559, budgetUsd: 0 },
    { segment: "Iraq", projPLUsd: 5045873.4329, realPLUsd: 2710763.729037, budgetUsd: 2990000 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 164000 },
    { segment: "Nigeria", projPLUsd: 87600, realPLUsd: 686564.17, budgetUsd: 0 },
  ],
  "2025-10": [
    { segment: "Arasa-Trabzon", projPLUsd: 264630.27484, realPLUsd: 198750.136851, budgetUsd: 85746 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225479 },
    { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: 3060246 },
    { segment: "Djibouti", projPLUsd: 233400, realPLUsd: 51493.18, budgetUsd: 229160 },
    { segment: "Ghana", projPLUsd: 11550, realPLUsd: 0, budgetUsd: 0 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -104027 },
    { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -47310 },
    { segment: "Iran payment", projPLUsd: 4093643.35236, realPLUsd: 3553222.34796, budgetUsd: 0 },
    { segment: "Iraq", projPLUsd: 3214852.1832, realPLUsd: 4471334.661181, budgetUsd: 4030000 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: -180060.93, budgetUsd: 523000 },
  ],
  "2025-11": [
    { segment: "Arasa-Trabzon", projPLUsd: 200948.3706, realPLUsd: 775134.99758, budgetUsd: 85778 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225587 },
    { segment: "Central America", projPLUsd: 8331390, realPLUsd: 17255701.414086, budgetUsd: -246639 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 340818 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -146595 },
    { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -47290 },
    { segment: "Iraq", projPLUsd: 4169509.4875, realPLUsd: 5427297.88473, budgetUsd: 4030000 },
    { segment: "Iraq Wheat", projPLUsd: 1290800, realPLUsd: 0, budgetUsd: 523000 },
    { segment: "Nigeria", projPLUsd: 0, realPLUsd: -505384.72, budgetUsd: 0 },
  ],
  "2025-12": [
    { segment: "Arasa-Trabzon", projPLUsd: 197477.5728, realPLUsd: 111211.879083, budgetUsd: 85803 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225720 },
    { segment: "Central America", projPLUsd: 8841300, realPLUsd: 0, budgetUsd: 1424486 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 199716 },
    { segment: "Eritrea", projPLUsd: 0, realPLUsd: 0, budgetUsd: 632000 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -149543 },
    { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -47210 },
    { segment: "Iraq", projPLUsd: 5455602.23152, realPLUsd: 3617996.725342, budgetUsd: 2307500 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 523000 },
    { segment: "Nigeria", projPLUsd: 769050, realPLUsd: 0, budgetUsd: 0 },
  ],
  "2026-01": [
    { segment: "Arasa-Trabzon", projPLUsd: 809338.021, realPLUsd: 386024.536091, budgetUsd: 85292 },
    { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: -253457 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 302063 },
    { segment: "Eritrea", projPLUsd: 0, realPLUsd: 0, budgetUsd: 572000 },
    { segment: "Ghana", projPLUsd: 46310, realPLUsd: -1022.2, budgetUsd: 0 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -245197.0 },
    { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -47290 },
    { segment: "Iran payment", projPLUsd: 0, realPLUsd: 937418.442528, budgetUsd: 0 },
    { segment: "Iraq", projPLUsd: 9308628.75758, realPLUsd: 6714962.889034, budgetUsd: 2990000 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 496000 },
  ],
  "2026-02": [
    { segment: "Arasa-Trabzon", projPLUsd: 157878.26, realPLUsd: 156693.310026, budgetUsd: 85345 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 223909 },
    { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: 1381804 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225496 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -170259 },
    { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -57840 },
    { segment: "Iran payment", projPLUsd: 1220903.97, realPLUsd: 0, budgetUsd: 0 },
    { segment: "Iraq", projPLUsd: 2707823.1, realPLUsd: 3073516.48602, budgetUsd: 4030000 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 496000 },
  ],
  "2026-03": [
    { segment: "Arasa-Trabzon", projPLUsd: 257400, realPLUsd: 15244.55379, budgetUsd: 85399 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 223536 },
    { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: -253099 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 338214 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -193936 },
    { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -95306 },
    { segment: "Iraq", projPLUsd: 0, realPLUsd: 0, budgetUsd: 4030000 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 496000 },
  ],
  "2026-04": [
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 224411 },
    { segment: "Central America", projPLUsd: 1003959.6, realPLUsd: 1101445.24, budgetUsd: -252473 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 228414 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -188000 },
    { segment: "Iran", projPLUsd: 0, realPLUsd: 0, budgetUsd: -54705 },
    { segment: "Iraq", projPLUsd: 0, realPLUsd: 1232666.2, budgetUsd: 4225000.0 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 496000 },
  ],
  "2026-05": [
    { segment: "Arasa-Trabzon", projPLUsd: 3396766.18, realPLUsd: 0, budgetUsd: 0 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 224628 },
    { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: -252269 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 309807 },
    { segment: "Eritrea", projPLUsd: 1235428.18455, realPLUsd: 1212058.376278, budgetUsd: 572000 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -160432 },
    { segment: "Iran", projPLUsd: 92222.45835, realPLUsd: 84545.408856, budgetUsd: -54705 },
    { segment: "Iraq", projPLUsd: 2469392.769, realPLUsd: 2585320.66, budgetUsd: 4030000 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 516000 },
  ],
  "2026-06": [
    { segment: "Arasa-Trabzon", projPLUsd: 1181886, realPLUsd: 0, budgetUsd: 0 },
    { segment: "CBOT Hedge", projPLUsd: 0, realPLUsd: 0, budgetUsd: 224775 },
    { segment: "Central America", projPLUsd: 0, realPLUsd: 0, budgetUsd: 1382851 },
    { segment: "Djibouti", projPLUsd: 0, realPLUsd: 0, budgetUsd: 225740 },
    { segment: "International", projPLUsd: 0, realPLUsd: 0, budgetUsd: -393252 },
    { segment: "Iran", projPLUsd: 822000, realPLUsd: 0, budgetUsd: -54707 },
    { segment: "Iraq", projPLUsd: 1430597.605695, realPLUsd: 282366.6, budgetUsd: 4030000 },
    { segment: "Iraq Wheat", projPLUsd: 0, realPLUsd: 0, budgetUsd: 516000 },
  ],
};
